import { BRAND } from '@config/brand';

const content = `# ${BRAND.name}

> ${BRAND.tagline} / ${BRAND.taglineEn}

## About

e-dietetyk.com is a Polish online dietitian platform that combines AI-powered meal planning with professional dietitian oversight. We create personalized nutrition plans (plany żywieniowe) based on clinical science, a verified database of 6,600+ Polish food products, and modern AI technology — all reviewed and approved by licensed dietitians.

## Services

- **AI-Powered Diet Plans** (plany żywieniowe AI): Personalized weekly meal plans generated by AI using clinical nutrition rules, then verified by a professional dietitian
- **Professional Dietitian Consultation** (konsultacja z dietetykiem): One-on-one consultation with a licensed clinical dietitian (399 PLN)
- **Monthly Nutrition Care** (opieka miesięczna): Ongoing AI + dietitian care subscription (129 PLN/month)
- **Annual Nutrition Care** (opieka roczna): Best-value annual plan (99 PLN/month)
- **Clinical Policy Engine**: 85 clinical nutrition rules + 16 red-flag safety checks built into every plan
- **OR-Tools Solver**: Mathematical optimization for meal diversity, macro balance, and nutrient coverage

## Key Facts

- **Location**: Poland (serving Polish and English-speaking clients)
- **Languages**: Polish (primary), English
- **Domain**: e-dietetyk.com
- **Founded**: 2025
- **Pricing**: from 99 PLN/month (annual) to 399 PLN (one-time consultation)
- **Technology**: AI diet planning (GPT-4.1 + OR-Tools CP-SAT solver) verified by licensed dietitians
- **Food Database**: 6,600+ verified Polish products with full nutrient profiles + glycemic index data
- **Recipe Database**: Curated recipes with macro/micronutrient data
- **Compliance**: RODO (GDPR) compliant, AES-256-GCM encryption for medical data
- **Safety**: Clinical Policy Engine with 85 rules, 16 red-flag checks, mandatory dietitian review

## Links

- [Homepage](https://${BRAND.domain}/pl)
- [Services & Pricing](https://${BRAND.domain}/pl/oferta)
- [FAQ](https://${BRAND.domain}/pl/faq)
- [About Us](https://${BRAND.domain}/pl/o-nas)
- [Blog](https://${BRAND.domain}/pl/blog)
- [Consultation](https://${BRAND.domain}/pl/konsultacja)
- [Full AI-readable version](https://${BRAND.domain}/llms-full.txt)

## Contact

- Email: ${BRAND.email}
- Phone: ${BRAND.phone}
- Facebook: ${BRAND.social.facebook}
- Instagram: ${BRAND.social.instagram}
`;

export async function GET() {
  return new Response(content.trim(), {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
