import type { RuleSeed } from './types';

export const ALLERGEN_SEEDS: RuleSeed[] = [
  // ─── EU 14 Allergen Rules (27.6.3 — enhanced with sources, versions, expanded keywords) ───
  // Source: Regulation (EU) No 1169/2011, Annex II — 14 mandatory allergens
  {
    name: 'Eliminacja glutenu',
    description: 'EU 1: Zboża zawierające gluten (pszenica, żyto, jęczmień, owies, orkisz, kamut)',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }, { ref: 'EAACI Food Allergy Guidelines', year: 2014 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['gluten'] },
    effects: [
      { type: 'EXCLUDE_PRODUCTS', flagKey: 'glutenFree', flagValue: false },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['pszenica', 'żyto', 'jęczmień', 'owies', 'orkisz', 'kamut', 'kasza manna', 'kuskus', 'bulgur', 'makaron', 'chleb', 'bułka', 'mąka pszenna', 'wheat', 'rye', 'barley', 'oats', 'spelt', 'semolina', 'couscous', 'bulgur', 'pasta', 'bread', 'flour'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia/nietolerancja glutenu (EU alergen nr 1): eliminacja pszenicy, żyta, jęczmienia, owsa, orkiszu, kamut. Dozwolone: ryż, kukurydza, gryka, amarant, quinoa, proso, tapioka. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja skorupiaków',
    description: 'EU 2: Skorupiaki i produkty pochodne (krewetki, kraby, homary, langusty)',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['shellfish', 'skorupiaki', 'krewetki', 'crustaceans'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['krewetka', 'krewetki', 'krab', 'homar', 'langusta', 'rak', 'shrimp', 'crab', 'lobster', 'crayfish', 'prawn', 'crustacean'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na skorupiaki (EU alergen nr 2): eliminacja krewetek, krabów, homarów, langust, raków. UWAGA: możliwa reaktywność krzyżowa z mięczakami. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja jaj',
    description: 'EU 3: Jaja i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['eggs', 'jajka', 'jaja', 'egg'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['jajko', 'jajka', 'jaje', 'białko jaja', 'żółtko', 'egg', 'eggs', 'omlet', 'omelette', 'frittata', 'majonezy', 'mayonnaise'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na jaja (EU alergen nr 3): eliminacja jaj i produktów jajecznych (majonez, biszkopt, lody, pankierowane). Sprawdzać etykiety — jaja w wielu produktach przetworzonych. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja ryb',
    description: 'EU 4: Ryby i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['fish', 'ryby', 'ryba'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['ryba', 'łosoś', 'tuńczyk', 'dorsz', 'makrela', 'śledź', 'halibut', 'pstrąg', 'sandacz', 'tilapia', 'sardynka', 'szprot', 'anchois', 'fish', 'salmon', 'tuna', 'cod', 'mackerel', 'herring', 'trout', 'anchovy', 'sardine'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na ryby (EU alergen nr 4): eliminacja wszystkich ryb i produktów rybnych. Rozważyć suplementację omega-3 z alg (EPA/DHA). Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Omega-3 z alg (EPA+DHA)', dose: '250-500 mg/d', reason: 'Alternatywne źródło omega-3 przy eliminacji ryb' },
    ],
  },
  {
    name: 'Eliminacja orzeszków ziemnych',
    description: 'EU 5: Orzeszki ziemne (arachidowe) i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '1.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }, { ref: 'EAACI Food Allergy Guidelines', year: 2014 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['peanut', 'orzeszki ziemne', 'arachidowe', 'orzech ziemny'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['orzeszek ziemny', 'orzeszki ziemne', 'arachidowy', 'masło orzechowe', 'peanut', 'peanuts', 'peanut butter', 'groundnut'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na orzeszki ziemne (EU alergen nr 5): eliminacja orzeszków ziemnych i produktów pochodnych (masło orzechowe, olej arachidowy). UWAGA: jeden z najczęstszych alergenów wywołujących anafilaksję. Sprawdzać etykiety. Źródło: Rozporządzenie (UE) 1169/2011, EAACI 2014', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja soi',
    description: 'EU 6: Soja i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['soy', 'soja', 'soybean'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['soja', 'tofu', 'tempeh', 'edamame', 'miso', 'natto', 'lecytyna sojowa', 'olej sojowy', 'sos sojowy', 'soy', 'soybean', 'soy sauce', 'soy lecithin', 'soy milk'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na soję (EU alergen nr 6): eliminacja soi i produktów sojowych (tofu, tempeh, sos sojowy, miso, lecytyna sojowa). Soja obecna w wielu produktach przetworzonych. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja mleka',
    description: 'EU 7: Mleko i produkty pochodne (w tym laktoza)',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['milk', 'mleko', 'lactose', 'laktoza', 'dairy', 'nabiał'] },
    effects: [
      { type: 'EXCLUDE_PRODUCTS', flagKey: 'lactoseFree', flagValue: false },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['mleko', 'jogurt', 'kefir', 'śmietana', 'twaróg', 'ser', 'masło', 'serwatka', 'kazeina', 'milk', 'yogurt', 'cream', 'cottage cheese', 'cheese', 'butter', 'whey', 'casein'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na białka mleka / nietolerancja laktozy (EU alergen nr 7): eliminacja mleka i produktów mlecznych. Przy alergii na białka mleka — pełna eliminacja (w tym masło, serwatka, kazeina). Przy nietolerancji laktozy — ser dojrzewający i masło zwykle tolerowane. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Wapń', dose: '800-1000 mg/d', reason: 'Uzupełnienie wapnia przy eliminacji nabiału — rozważyć napoje roślinne wzbogacone w Ca' },
    ],
  },
  {
    name: 'Eliminacja orzechów',
    description: 'EU 8: Orzechy (migdały, laskowe, włoskie, nerkowce, pekan, brazylijskie, pistacje, makadamia)',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['nuts', 'orzechy', 'tree nuts'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['orzech', 'migdał', 'orzech laskowy', 'orzech włoski', 'nerkowiec', 'kasztan', 'pistacja', 'pekan', 'makadamia', 'orzech brazylijski', 'marcepan', 'nut', 'almond', 'walnut', 'cashew', 'pistachio', 'pecan', 'hazelnut', 'macadamia', 'brazil nut', 'marzipan'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na orzechy (EU alergen nr 8): eliminacja migdałów, orzechów laskowych, włoskich, nerkowców, pekan, brazylijskich, pistacji, makadamia. Sprawdzać: marcepan, nougat, pralinki, oleje orzechowe. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja selera',
    description: 'EU 9: Seler i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['celery', 'seler'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['seler', 'seler naciowy', 'seler korzeniowy', 'celery', 'celeriac'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na seler (EU alergen nr 9): eliminacja selera naciowego i korzeniowego. UWAGA: seler częsty w przyprawach, bulionach, zupach instant. Możliwa reaktywność krzyżowa z pyłkiem brzozy (zespół brzoza-seler). Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja gorczycy',
    description: 'EU 10: Gorczyca i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['mustard', 'gorczyca'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['gorczyca', 'musztarda', 'mustard', 'nasiona gorczycy', 'olej gorczycowy', 'mustard seed', 'mustard oil'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na gorczycę (EU alergen nr 10): eliminacja gorczycy i musztardy. Gorczyca może być ukryta w sosach, dressingach, marynatach, curry. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja sezamu',
    description: 'EU 11: Nasiona sezamu i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '2.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['sesame', 'sezam'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['sezam', 'tahini', 'tahina', 'halwa', 'sesame', 'sesame oil', 'tahini', 'halvah'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na sezam (EU alergen nr 11): eliminacja nasion sezamu, tahini, halwy, oleju sezamowego. Sezam częsty w pieczywie, bułkach, hummusie, kuchni azjatyckiej. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja dwutlenku siarki i siarczyny',
    description: 'EU 12: Dwutlenek siarki i siarczyny w stężeniu >10 mg/kg lub >10 mg/l (w przeliczeniu na SO₂)',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '1.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['sulfite', 'siarczyny', 'dwutlenek siarki', 'sulfur dioxide', 'so2'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['wino', 'suszone owoce', 'suszone morele', 'wine', 'dried fruit', 'dried apricots', 'sulfite', 'siarczyny'] },
      { type: 'CLINICAL_NOTE', note: 'Wrażliwość na siarczyny (EU alergen nr 12): unikać produktów z dodatkiem SO₂/siarczyny (E220-E228). Częste w: winie, suszone owoce, konserwy, soki, ocet winny. Szczególnie ważne u astmatyków. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja łubinu',
    description: 'EU 13: Łubin i produkty pochodne',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '1.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['lupin', 'łubin', 'lupine'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['łubin', 'mąka łubinowa', 'lupin', 'lupine', 'lupin flour'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na łubin (EU alergen nr 13): eliminacja łubinu i mąki łubinowej. Łubin stosowany w pieczywie bezglutenowym, makaronach, wegetariańskich zamiennikach. UWAGA: reaktywność krzyżowa z orzeszkami ziemnymi! Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Eliminacja mięczaków',
    description: 'EU 14: Mięczaki i produkty pochodne (ośmiornice, kalmary, małże, ślimaki)',
    type: 'POLICY', severity: 'LOW', priority: 100,
    version: '1.0', category: 'allergen',
    sources: [{ ref: 'Regulation (EU) No 1169/2011, Annex II', year: 2011 }],
    conditions: { type: 'HAS_ALLERGY', terms: ['mollusks', 'mięczaki', 'małże', 'ośmiornica', 'kałamarnica', 'mollusc'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['małż', 'małże', 'ostryga', 'ośmiornica', 'kałamarnica', 'ślimak', 'przegrzebek', 'omułek', 'mussel', 'oyster', 'octopus', 'squid', 'snail', 'scallop', 'clam', 'mollusc'] },
      { type: 'CLINICAL_NOTE', note: 'Alergia na mięczaki (EU alergen nr 14): eliminacja małży, ostryg, ośmiornic, kalmarów, ślimaków, przegrzebków. UWAGA: możliwa reaktywność krzyżowa ze skorupiakami. Źródło: Rozporządzenie (UE) 1169/2011', category: 'RESTRICTION' },
    ],
  },
];
