import type { RuleSeed } from './types';

export const DIGESTIVE_SEEDS: RuleSeed[] = [
  // Digestive / GI (27.5)
  // 27.5.1 GERD (ULEPSZENIE)
  {
    name: 'GERD (Refluks)',
    description: 'Refluks żołądkowo-przełykowy — unikanie triggerów, mniejsze porcje, przerwa 3h przed snem',
    type: 'POLICY', severity: 'LOW', priority: 65,
    version: '2.0',
    category: 'digestive',
    sources: [{ ref: 'ACG Clinical Guideline: Diagnosis and Management of GERD', year: 2022 }],
    conditions: { type: 'HAS_CONDITION', terms: ['gerd', 'refluks', 'reflux', 'choroba refluksowa', 'reflux disease'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['pomidor', 'cytrus', 'cytryna', 'pomarańcza', 'mięta', 'czekolada', 'kawa', 'alkohol', 'piwo', 'wino', 'tomato', 'citrus', 'lemon', 'orange', 'mint', 'chocolate', 'coffee', 'alcohol', 'beer', 'wine'] },
      { type: 'MEAL_DISTRIBUTION', nutrient: 'fat', maxPerMealPct: 25 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'saturatedFat', scope: 'DAILY_TOTAL', max: 22 },
      { type: 'CLINICAL_NOTE', note: 'GERD: unikanie pomidorów, cytrusów, kawy, czekolady, mięty, alkoholu, tłustych potraw; mniejsze posiłki 5-6x/d, ostatni posiłek min. 3h przed snem, unikanie leżenia po jedzeniu. Źródło: ACG 2022 Guidelines', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: podwyższona pozycja głowy podczas snu (15-20cm), unikanie obcisłej odzieży po posiłku, chodzenie po jedzeniu zamiast siedzenia', category: 'RECOMMENDATION' },
    ],
  },
  // 27.5.2 Choroba wrzodowa żołądka (NOWA)
  {
    name: 'Choroba wrzodowa żołądka',
    description: 'Choroba wrzodowa żołądka — lekkostrawna, małe częste posiłki, probiotyki',
    type: 'POLICY', severity: 'LOW', priority: 68,
    version: '1.0',
    category: 'digestive',
    sources: [{ ref: 'ACG Clinical Guideline: Treatment of Helicobacter pylori Infection', year: 2017 }],
    conditions: { type: 'HAS_CONDITION', terms: ['gastric ulcer', 'wrzód żołądka', 'wrzod zoladka', 'choroba wrzodowa żołądka', 'choroba wrzodowa zoladka', 'peptic ulcer'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'wódka', 'alcohol', 'beer', 'wine', 'vodka', 'kawa', 'coffee', 'ostre przyprawy', 'chili', 'pieprz cayenne', 'hot pepper', 'ocet', 'vinegar'] },
      { type: 'MEAL_DISTRIBUTION', nutrient: 'fat', maxPerMealPct: 20 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowFodmap', flagValue: true },
      { type: 'CLINICAL_NOTE', note: 'Choroba wrzodowa żołądka: dieta lekkostrawna, 5-6 małych posiłków/d, unikanie alkoholu, kawy na pusty żołądek, ostrych przypraw i NLPZ. Probiotyki (Lactobacillus, Saccharomyces boulardii) mogą wspierać leczenie. Źródło: ACG 2017', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: gotowanie na parze, duszenie; unikanie smażenia; jedzenie w spokoju, dokładne gryzienie', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Probiotyk (Lactobacillus + S. boulardii)', dose: '1-2 kapsułki/d', reason: 'Wsparcie bariery śluzówkowej żołądka (ACG 2017)' },
    ],
  },
  // 27.5.3 Choroba wrzodowa dwunastnicy (NOWA)
  {
    name: 'Choroba wrzodowa dwunastnicy',
    description: 'Choroba wrzodowa dwunastnicy — jak żołądka + unikanie długich przerw między posiłkami',
    type: 'POLICY', severity: 'LOW', priority: 67,
    version: '1.0',
    category: 'digestive',
    sources: [{ ref: 'ACG Clinical Guideline: Treatment of Helicobacter pylori Infection', year: 2017 }],
    conditions: { type: 'HAS_CONDITION', terms: ['duodenal ulcer', 'wrzód dwunastnicy', 'wrzod dwunastnicy', 'choroba wrzodowa dwunastnicy'] },
    effects: [
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'wódka', 'alcohol', 'beer', 'wine', 'vodka', 'kawa', 'coffee', 'ostre przyprawy', 'chili', 'pieprz cayenne', 'hot pepper', 'ocet', 'vinegar'] },
      { type: 'MEAL_DISTRIBUTION', nutrient: 'fat', maxPerMealPct: 20 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowFodmap', flagValue: true },
      { type: 'CLINICAL_NOTE', note: 'Choroba wrzodowa dwunastnicy: dieta lekkostrawna, 5-6 małych posiłków/d, unikanie długich przerw między posiłkami (>4h), alkoholu, kawy na pusty żołądek, ostrych przypraw. Źródło: ACG 2017', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Kluczowe: regularne posiłki co 3-4h zapobiegają podrażnieniu przez kwas żołądkowy na pusty dwunastnicę', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Probiotyk (Lactobacillus + S. boulardii)', dose: '1-2 kapsułki/d', reason: 'Wsparcie eradykacji H. pylori i regeneracji śluzówki' },
    ],
  },
  // 27.5.4 IBS-C (NOWA)
  {
    name: 'IBS-C (zaparciowy)',
    description: 'IBS z dominującymi zaparciami — błonnik rozpuszczalny 20-25g/d, nawodnienie, low-FODMAP opcjonalnie',
    type: 'POLICY', severity: 'LOW', priority: 70,
    version: '1.0',
    category: 'digestive',
    sources: [
      { ref: 'ACG Clinical Guideline: Management of Irritable Bowel Syndrome', year: 2021 },
      { ref: 'Monash University Low FODMAP Diet', year: 2023 },
    ],
    conditions: { type: 'HAS_CONDITION', terms: ['ibs-c', 'ibs zaparciowy', 'ibs constipation', 'jelito drażliwe zaparciowe', 'ibs z zaparciami'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 20, max: 25 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cebula', 'czosnek', 'por', 'grzyb', 'onion', 'garlic', 'leek', 'mushroom'] },
      { type: 'CLINICAL_NOTE', note: 'IBS-C: błonnik ROZPUSZCZALNY 20-25g/d (psyllium, owies, siemię lniane), nawodnienie 2-2.5L/d, regularne posiłki. Low-FODMAP jeśli brak odpowiedzi na błonnik. Źródło: ACG 2021 IBS Guidelines, Monash University', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: psyllium (łuski babki jajowatej) 5-10g/d — najlepiej udokumentowany błonnik w IBS-C. Unikać błonnika nierozpuszczalnego (otręby pszenne) — może nasilać objawy.', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Psyllium (babka jajowata)', dose: '5-10 g/d', reason: 'Błonnik rozpuszczalny o najlepszych dowodach w IBS-C (ACG 2021)' },
    ],
  },
  // 27.5.5 IBS-D (NOWA)
  {
    name: 'IBS-D (biegunkowy)',
    description: 'IBS z dominującymi biegunkami — low-FODMAP, ograniczenie błonnika nierozpuszczalnego',
    type: 'POLICY', severity: 'LOW', priority: 71,
    version: '1.0',
    category: 'digestive',
    sources: [
      { ref: 'ACG Clinical Guideline: Management of Irritable Bowel Syndrome', year: 2021 },
      { ref: 'Monash University Low FODMAP Diet', year: 2023 },
    ],
    conditions: { type: 'HAS_CONDITION', terms: ['ibs-d', 'ibs biegunkowy', 'ibs diarrhea', 'jelito drażliwe biegunkowe', 'ibs z biegunkami'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowFodmap', flagValue: true },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 15, max: 22 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cebula', 'czosnek', 'por', 'grzyb', 'jabłko', 'gruszka', 'kofeina', 'kawa', 'alkohol', 'onion', 'garlic', 'leek', 'mushroom', 'apple', 'pear', 'caffeine', 'coffee', 'alcohol', 'sorbitol', 'ksylitol', 'xylitol'] },
      { type: 'CLINICAL_NOTE', note: 'IBS-D: dieta low-FODMAP (ścisła eliminacja 4-6 tygodni, potem reintrodukcja), ograniczenie błonnika NIEROZPUSZCZALNEGO, unikanie kofeiny, alkoholu, laktozy, sorbitolu. Źródło: ACG 2021, Monash University', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Fazy diety low-FODMAP: 1) Eliminacja (4-6 tyg), 2) Reintrodukcja (6-8 tyg, po jednym FODMAP), 3) Personalizacja. Nie stosować long-term bez reintrodukcji.', category: 'RECOMMENDATION' },
    ],
  },
  // 27.5.6 IBS-M (NOWA)
  {
    name: 'IBS-M (mieszany)',
    description: 'IBS mieszany — low-FODMAP jako baza, błonnik rozpuszczalny umiarkowanie',
    type: 'POLICY', severity: 'LOW', priority: 70,
    version: '1.0',
    category: 'digestive',
    sources: [{ ref: 'ACG Clinical Guideline: Management of Irritable Bowel Syndrome', year: 2021 }],
    conditions: { type: 'HAS_CONDITION', terms: ['ibs-m', 'ibs mieszany', 'ibs mixed', 'jelito drażliwe mieszane', 'ibs z zaparciami i biegunkami'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowFodmap', flagValue: true },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 18, max: 25 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cebula', 'czosnek', 'por', 'grzyb', 'onion', 'garlic', 'leek', 'mushroom'] },
      { type: 'CLINICAL_NOTE', note: 'IBS-M: dieta low-FODMAP jako baza, błonnik rozpuszczalny umiarkowanie (18-25g/d), indywidualizacja na podstawie dominujących objawów. Źródło: ACG 2021', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Objawy mieszane wymagają elastycznego podejścia — monitorować, które posiłki nasilają zaparcia vs biegunki i dostosowywać indywidualnie', category: 'RECOMMENDATION' },
    ],
  },
  // IBS ogólny (zachowany dla nieokreślonego podtypu)
  {
    name: 'IBS (Zespół jelita drażliwego)',
    description: 'IBS bez określonego podtypu — preferencja produktów low-FODMAP',
    type: 'POLICY', severity: 'LOW', priority: 69,
    version: '2.0',
    category: 'digestive',
    sources: [{ ref: 'ACG Clinical Guideline: Management of Irritable Bowel Syndrome', year: 2021 }],
    conditions: { type: 'HAS_CONDITION', terms: ['ibs', 'jelito drażliwe', 'jelita drażliwego', 'irritable bowel'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowFodmap', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cebula', 'czosnek', 'por', 'grzyb', 'onion', 'garlic', 'leek', 'mushroom'] },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 20, max: 30 },
      { type: 'CLINICAL_NOTE', note: 'IBS (nieokreślony podtyp): preferowane produkty low-FODMAP, unikanie cebuli/czosnku/grzybów, umiarkowany błonnik (20-30g). Zalecane określenie podtypu (IBS-C/D/M) dla lepszej personalizacji.', category: 'RESTRICTION' },
    ],
  },
  // 27.5.7 Choroba Leśniowskiego-Crohna (NOWA)
  {
    name: 'Choroba Leśniowskiego-Crohna',
    description: 'Choroba Crohna — stage: remisja vs zaostrzenie, suplementacja B12/Fe/D3/Ca/Zn',
    type: 'POLICY', severity: 'MODERATE', priority: 78,
    version: '1.0',
    category: 'digestive',
    sources: [
      { ref: 'ECCO-ESPEN Guideline on Clinical Nutrition in IBD', year: 2020 },
      { ref: 'ESPEN Practical Guideline: Clinical Nutrition in IBD', year: 2020 },
    ],
    conditions: { type: 'HAS_CONDITION', terms: ['crohn', 'leśniowski', 'lesniowski', 'choroba crohna', 'crohn disease', 'crohns'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'MULTIPLY', value: 1.2 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 15, max: 25 },
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'alcohol', 'beer', 'wine', 'fast food', 'chipsy', 'chips', 'ultra-przetworzone', 'ultra-processed'] },
      { type: 'CLINICAL_NOTE', note: 'Choroba Crohna — remisja: dieta śródziemnomorska, unikanie ultra-przetworzonej żywności, białko 1.2-1.5g/kg. Zaostrzenie: dieta lekkostrawna, niskobłonnikowa, płynna/papkowata. RED FLAG: HIGH w zaostrzeniu. Źródło: ECCO/ESPEN 2020', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'W remisji: pełnoziarniste, warzywa gotowane, owoce bez skórki, ryby. W zaostrzeniu: unikać surowych warzyw, orzechów, nasion, produktów z dużą ilością błonnika nierozpuszczalnego.', category: 'INFO' },
      { type: 'CLINICAL_NOTE', note: 'UWAGA: Choroba Crohna wymaga regularnej opieki gastroenterologicznej. Zaostrzenie = RED FLAG HIGH.', category: 'WARNING' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina B12', dose: '1000 µg/tyg (sublingual)', reason: 'Częsty niedobór przy zajęciu jelita krętego (ECCO/ESPEN 2020)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Żelazo', dose: 'wg poziomu ferrytyny', reason: 'Anemia częsta w IBD — preferować iv jeśli nietolerancja doustnego' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000-4000 IU/d', reason: 'Częsty niedobór, działanie immunomodulujące' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Cynk', dose: '25-50 mg/d', reason: 'Wsparcie gojenia śluzówki i odporności' },
    ],
  },
  // 27.5.8 Wrzodziejące zapalenie jelita grubego (NOWA)
  {
    name: 'Wrzodziejące zapalenie jelita grubego',
    description: 'Colitis ulcerosa — stage: remisja vs zaostrzenie, suplementacja Fe/D3/kwas foliowy',
    type: 'POLICY', severity: 'MODERATE', priority: 77,
    version: '1.0',
    category: 'digestive',
    sources: [{ ref: 'ECCO Guideline on Therapeutics in Ulcerative Colitis', year: 2022 }],
    conditions: { type: 'HAS_CONDITION', terms: ['ulcerative colitis', 'colitis ulcerosa', 'wrzodziejące zapalenie', 'wrzodziejace zapalenie', 'wzjg', 'uc'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'MULTIPLY', value: 1.2 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 15, max: 25 },
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'alcohol', 'beer', 'wine', 'fast food', 'chipsy', 'chips', 'ultra-przetworzone', 'ultra-processed'] },
      { type: 'CLINICAL_NOTE', note: 'Colitis ulcerosa — remisja: normalna dieta z unikaniem indywidualnych trigger foods, błonnik umiarkowany. Zaostrzenie: dieta niskobłonnikowa, niskoresidual, RED FLAG: HIGH. Źródło: ECCO 2022', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Remisja: preferować gotowane warzywa, owoce bez skórki, białko chude. Zaostrzenie: unikać surowych warzyw, orzechów, nasion, ostrych przypraw, laktozy.', category: 'INFO' },
      { type: 'CLINICAL_NOTE', note: 'UWAGA: Zaostrzenie colitis ulcerosa = RED FLAG HIGH — wymaga opieki gastroenterologicznej.', category: 'WARNING' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Żelazo', dose: 'wg poziomu ferrytyny', reason: 'Anemia z utraty krwi typowa w WZJG (ECCO 2022)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000 IU/d', reason: 'Częsty niedobór, działanie immunomodulujące w IBD' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Kwas foliowy', dose: '400-800 µg/d', reason: 'Niedobór przy terapii sulfasalazyną, profilaktyka raka jelita grubego' },
    ],
  },
  // 27.5.9 SIBO (NOWA)
  {
    name: 'SIBO',
    description: 'Przerost bakteryjny jelita cienkiego — low-FODMAP eliminacja, małe częste posiłki, przerwy 4h',
    type: 'POLICY', severity: 'LOW', priority: 72,
    version: '1.0',
    category: 'digestive',
    sources: [{ ref: 'ACG Clinical Guideline: SIBO', year: 2020 }],
    conditions: { type: 'HAS_CONDITION', terms: ['sibo', 'przerost bakteryjny', 'small intestinal bacterial overgrowth', 'bakteryjny przerost'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'lowFodmap', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 12, max: 20 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cebula', 'czosnek', 'por', 'grzyb', 'kapusta', 'brokuły', 'kalafior', 'jabłko', 'gruszka', 'onion', 'garlic', 'leek', 'mushroom', 'cabbage', 'broccoli', 'cauliflower', 'apple', 'pear', 'prebiotyk', 'prebiotic', 'inulina', 'inulin'] },
      { type: 'CLINICAL_NOTE', note: 'SIBO: dieta low-FODMAP faza eliminacji (4-6 tyg), unikanie prebiotyków i nadmiaru błonnika fermentowalnego, małe porcje, przerwy min. 4h między głównymi posiłkami (MMC — migrujący kompleks motoryczny). Źródło: ACG 2020 SIBO Guidelines', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: 3 główne posiłki z 4h przerwami (aktywacja MMC), unikanie ciągłego podjadania. Po leczeniu antybiotykowym: stopniowa reintrodukcja FODMAP.', category: 'RECOMMENDATION' },
    ],
  },
  // 27.5.10 Zaparcia przewlekłe (NOWA)
  {
    name: 'Zaparcia przewlekłe',
    description: 'Zaparcia przewlekłe bez IBS — błonnik 25-35g/d stopniowo, nawodnienie 2-2.5L/d',
    type: 'POLICY', severity: 'LOW', priority: 60,
    version: '1.0',
    category: 'digestive',
    sources: [
      { ref: 'WGO Global Guideline: Constipation', year: 2010 },
      { ref: 'ACG Clinical Guideline: Management of Chronic Constipation', year: 2021 },
    ],
    conditions: { type: 'HAS_CONDITION', terms: ['constipation', 'zaparcia', 'zaparcie', 'zaparcia przewlekłe', 'chronic constipation'] },
    effects: [
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25, max: 35 },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'CLINICAL_NOTE', note: 'Zaparcia przewlekłe: błonnik 25-35g/d (zwiększać stopniowo o 5g/tyg!), nawodnienie 2-2.5L/d, produkty pełnoziarniste, warzywa, owoce, nasiona. Źródło: WGO 2010, ACG 2021', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: siemię lniane 2 łyżki/d, suszone śliwki 5-6 szt/d, kefir/jogurt naturalny, regularna aktywność fizyczna (30 min/d)', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Probiotyk (Bifidobacterium lactis)', dose: '10^9-10^10 CFU/d', reason: 'Poprawa częstości wypróżnień (WGO 2010)' },
    ],
  },
  // 27.5.11 Biegunki przewlekłe (NOWA)
  {
    name: 'Biegunki przewlekłe',
    description: 'Biegunki przewlekłe bez IBS — dieta BRAT, elektrolity, unikanie laktozy/kofeiny/sorbitolu',
    type: 'POLICY', severity: 'LOW', priority: 62,
    version: '1.0',
    category: 'digestive',
    sources: [
      { ref: 'ACG Clinical Guideline: Chronic Diarrhea', year: 2019 },
      { ref: 'WGO Global Guideline: Acute Diarrhea', year: 2012 },
    ],
    conditions: { type: 'HAS_CONDITION', terms: ['diarrhea', 'biegunka', 'biegunki', 'biegunki przewlekłe', 'chronic diarrhea'] },
    effects: [
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 10, max: 20 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['kofeina', 'kawa', 'caffeine', 'coffee', 'alkohol', 'alcohol', 'sorbitol', 'ksylitol', 'xylitol', 'sok owocowy', 'fruit juice'] },
      { type: 'PREFER_PRODUCTS', flagKey: 'ibsFriendly', flagValue: true },
      { type: 'CLINICAL_NOTE', note: 'Biegunki przewlekłe: dieta BRAT jako baza (banany, ryż, jabłko gotowane, tosty), uzupełnienie elektrolitów, unikanie laktozy, kofeiny, sorbitolu, nadmiaru błonnika. Źródło: ACG, WGO', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: gotowany ryż biały, marchew gotowana, banany, ziemniaki, chude mięso (kurczak, indyk), probiotyki. Nawodnienie z elektrolitami kluczowe.', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Probiotyk (Saccharomyces boulardii)', dose: '250-500 mg 2x/d', reason: 'Najlepiej udokumentowany probiotyk w biegunkach (WGO, Cochrane)' },
    ],
  },
  // Zachowane oryginalne
  {
    name: 'Celiakia',
    description: 'Pacjent zgłosił celiakię — bezwzględna eliminacja glutenu',
    type: 'POLICY', severity: 'LOW', priority: 100,
    category: 'digestive',
    conditions: { type: 'HAS_CONDITION', terms: ['celiac', 'celiakia'] },
    effects: [
      { type: 'EXCLUDE_PRODUCTS', flagKey: 'glutenFree', flagValue: false },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['pszenica', 'żyto', 'jęczmień', 'owies', 'kasza manna', 'kuskus', 'wheat', 'rye', 'barley', 'oats', 'semolina', 'couscous'] },
      { type: 'CLINICAL_NOTE', note: 'Celiakia: bezwzględna eliminacja glutenu — wszystkie źródła pszenicy, żyta, jęczmienia i potencjalnie owsa', category: 'RESTRICTION' },
    ],
  },
  {
    name: 'Nietolerancja laktozy (z wywiadu)',
    description: 'Pacjent zgłosił nietolerancję laktozy w problemach trawiennych',
    type: 'POLICY', severity: 'LOW', priority: 95,
    category: 'digestive',
    conditions: { type: 'HAS_CONDITION', terms: ['lactose_intolerance', 'nietolerancja laktozy'] },
    effects: [
      { type: 'EXCLUDE_PRODUCTS', flagKey: 'lactoseFree', flagValue: false },
      { type: 'CLINICAL_NOTE', note: 'Nietolerancja laktozy: wykluczono produkty mleczne zawierające laktozę', category: 'RESTRICTION' },
    ],
  },
];
