import type { RuleSeed } from './types';

export const LIVER_SEEDS: RuleSeed[] = [
  // ─── Liver / Hepatic rules (27.4) ──────────────────────────────────────────
  // 27.4.1 NAFLD
  {
    name: 'NAFLD',
    description: 'Niealkoholowa stłuszczeniowa choroba wątroby — redukcja masy 7-10%, ograniczenie fruktozy, dieta śródziemnomorska',
    type: 'POLICY', severity: 'LOW', priority: 72,
    version: '1.0', category: 'liver',
    sources: [{ ref: 'EASL/EASD/EASO Clinical Practice Guidelines on NAFLD', year: 2016 }, { ref: 'AASLD Practice Guidance on NAFLD', year: 2023 }],
    conditions: { type: 'HAS_CONDITION', terms: ['nafld', 'stłuszczenie wątroby', 'stluszczenie watroby', 'niealkoholowa stłuszczeniowa', 'fatty liver', 'non-alcoholic fatty liver'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetKcal', operation: 'ADD', value: -500 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 5 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'saturatedFat', scope: 'DAILY_TOTAL', max: 20 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25, max: 35 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'wódka', 'alcohol', 'beer', 'wine', 'vodka', 'syrop fruktozowy', 'fruktoza', 'fructose syrup', 'high fructose', 'napój gazowany', 'soda', 'cola', 'fast food', 'frytki', 'fries'] },
      { type: 'CLINICAL_NOTE', note: 'NAFLD: redukcja masy ciała o 7-10% (najskuteczniejsza interwencja), dieta śródziemnomorska, ograniczenie fruktozy i cukrów prostych, eliminacja alkoholu, błonnik 25-35g/d. Źródło: EASL/EASD/EASO 2016, AASLD 2023', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane: oliwa z oliwek, orzechy, ryby tłuste, kawa (2-3 filiżanki/d — działanie hepatoprotekcyjne), warzywa, produkty pełnoziarniste', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina E', dose: '800 IU/d', reason: 'Działanie przeciwutleniające w stłuszczeniu wątroby (AASLD 2023 — tylko bez cukrzycy)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Omega-3 (EPA+DHA)', dose: '1-2 g/d', reason: 'Redukcja stłuszczenia i triglicerydów wątrobowych' },
    ],
  },
  // 27.4.2 NASH
  {
    name: 'NASH',
    description: 'Niealkoholowe stłuszczeniowe zapalenie wątroby — jak NAFLD + bardziej restrykcyjne, wit. E',
    type: 'POLICY', severity: 'MODERATE', priority: 76,
    version: '1.0', category: 'liver',
    sources: [{ ref: 'EASL/EASD/EASO Clinical Practice Guidelines', year: 2016 }, { ref: 'AASLD Practice Guidance', year: 2023 }, { ref: 'PIVENS Trial (Sanyal et al.)', year: 2010 }],
    conflictsWith: ['NAFLD'],
    conditions: { type: 'HAS_CONDITION', terms: ['nash', 'stłuszczeniowe zapalenie wątroby', 'stluszczeniowe zapalenie watroby', 'non-alcoholic steatohepatitis', 'steatohepatitis'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetKcal', operation: 'ADD', value: -500 },
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'MULTIPLY', value: 1.2 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 4 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'saturatedFat', scope: 'DAILY_TOTAL', max: 16 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25, max: 35 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'wódka', 'alcohol', 'beer', 'wine', 'vodka', 'syrop fruktozowy', 'fruktoza', 'fructose syrup', 'high fructose', 'napój gazowany', 'soda', 'cola', 'fast food', 'frytki', 'fries', 'słodycze', 'candy', 'cukier', 'sugar'] },
      { type: 'CLINICAL_NOTE', note: 'NASH: stan zapalny wątroby — redukcja masy 7-10%, bezwzględna eliminacja alkoholu, tłuszcze nasycone <7% energii, cukry proste minimalne, dieta śródziemnomorska. Źródło: EASL/EASD/EASO 2016, AASLD 2023', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'UWAGA: NASH może prowadzić do włóknienia i marskości. Regularna kontrola hepatologiczna obowiązkowa. Białko 1.2-1.5g/kg dla ochrony masy mięśniowej przy redukcji.', category: 'WARNING' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina E', dose: '800 IU/d', reason: 'Redukcja stanu zapalnego w NASH (AASLD 2023 — potwierdzone w badaniu PIVENS)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Omega-3 (EPA+DHA)', dose: '2 g/d', reason: 'Działanie przeciwzapalne i redukcja stłuszczenia' },
    ],
  },
  // 27.4.3 Marskość wątroby
  {
    name: 'Marskość wątroby',
    description: 'Marskość wątroby — białko 1.2-1.5g/kg, małe częste posiłki, sód <2g przy wodobrzuszu',
    type: 'POLICY', severity: 'HIGH', priority: 82,
    version: '1.0', category: 'liver',
    sources: [{ ref: 'EASL CPG on Nutrition in Chronic Liver Disease', year: 2019 }, { ref: 'ESPEN Guideline on Liver Disease', year: 2020 }],
    conditions: { type: 'HAS_CONDITION', terms: ['cirrhosis', 'marskość wątroby', 'marskosc watroby', 'marskość', 'liver cirrhosis'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'MULTIPLY', value: 1.3 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sodium', scope: 'DAILY_TOTAL', max: 2000 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 20, max: 30 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSodium', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'wódka', 'alcohol', 'beer', 'wine', 'vodka', 'surowe mięso', 'tatar', 'sushi', 'raw meat', 'raw fish', 'solony', 'marynowany', 'salted', 'pickled'] },
      { type: 'CLINICAL_NOTE', note: 'Marskość wątroby: białko 1.2-1.5g/kg/d (zapobieganie sarkopenii), 4-6 małych posiłków/d (w tym przekąska nocna!), sód <2g/d przy wodobrzuszu/obrzękach, bezwzględna eliminacja alkoholu. Źródło: EASL 2019 CPG Nutrition in CLD, ESPEN 2020', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Kompensowana: normalna dieta z wyższym białkiem. Dekompensowana (wodobrzusze, obrzęki): ścisła restrykcja sodu <2g, rozważyć restrykcję płynów. Przekąska nocna (50g węglowodanów) zapobiega katabolizmowi nocnemu.', category: 'INFO' },
      { type: 'CLINICAL_NOTE', note: 'UWAGA: Pacjent z marskością wymaga regularnej opieki hepatologicznej. Nie ograniczać białka (dawne zalecenia) — sarkopenia pogarsza rokowanie.', category: 'WARNING' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'BCAA (aminokwasy rozgałęzione)', dose: '0.25 g/kg/d', reason: 'Poprawa syntezy białek, zapobieganie sarkopenii i encefalopatii (ESPEN 2020)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000-4000 IU/d', reason: 'Częsty głęboki niedobór w marskości' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Cynk', dose: '50 mg/d', reason: 'Częsty niedobór, wspiera metabolizm amoniaku' },
    ],
  },
  // 27.4.4 Encefalopatia wątrobowa (RED FLAG CRITICAL)
  {
    name: 'Encefalopatia wątrobowa',
    description: 'Encefalopatia wątrobowa — RED FLAG CRITICAL, białko roślinne > zwierzęce, BCAA',
    type: 'POLICY', severity: 'HIGH', priority: 92,
    version: '1.0', category: 'liver',
    sources: [{ ref: 'EASL CPG on Hepatic Encephalopathy', year: 2022 }, { ref: 'ISHEN Consensus', year: 2014 }, { ref: 'ESPEN Guideline on Liver Disease', year: 2020 }],
    conditions: { type: 'HAS_CONDITION', terms: ['hepatic encephalopathy', 'encefalopatia wątrobowa', 'encefalopatia watrobowa', 'encefalopatia', 'encephalopathy'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'MULTIPLY', value: 1.2 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sodium', scope: 'DAILY_TOTAL', max: 2000 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25, max: 35 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSodium', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'piwo', 'wino', 'wódka', 'alcohol', 'beer', 'wine', 'vodka', 'surowe mięso', 'tatar', 'raw meat', 'czerwone mięso', 'wołowina', 'wieprzowina', 'beef', 'pork', 'red meat'] },
      { type: 'CLINICAL_NOTE', note: 'Encefalopatia wątrobowa: NIE ograniczać białka (1.2-1.5g/kg/d), preferować białko roślinne (strączkowe, tofu) i nabiał nad mięso czerwone, 4-6 małych posiłków + przekąska nocna, błonnik 25-35g/d (wspiera eliminację amoniaku). Źródło: EASL 2022 HE Guidelines, ISHEN Consensus, ESPEN 2020', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'UWAGA KRYTYCZNA: Encefalopatia wątrobowa jest stanem zagrożenia życia. Plan dietetyczny MUSI być weryfikowany przez hepatologa. Nie generować automatycznie.', category: 'WARNING' },
      { type: 'CLINICAL_NOTE', note: 'Hierarchia źródeł białka: 1) roślinne (soja, strączkowe) — generują mniej amoniaku, 2) nabiał, 3) ryby, 4) drób biały. Unikać: czerwone mięso, podroby.', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'BCAA (aminokwasy rozgałęzione)', dose: '0.25 g/kg/d', reason: 'Poprawa stanu odżywienia i redukcja epizodów encefalopatii (EASL 2022, ESPEN 2020)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Cynk', dose: '50 mg/d', reason: 'Kofaktor cyklu mocznikowego — wspiera eliminację amoniaku' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000-4000 IU/d', reason: 'Głęboki niedobór typowy w zaawansowanej chorobie wątroby' },
    ],
  },
];
