import type { RuleSeed } from './types';

export const METABOLIC_SEEDS: RuleSeed[] = [
  // ─── Metabolic rules (27.2) ─────────────────────────────────────────────
  // 27.2.1 Otyłość
  {
    name: 'Otyłość',
    description: 'BMI >= 30 — deficyt kaloryczny, wysokie białko, błonnik',
    type: 'POLICY', severity: 'LOW', priority: 78,
    version: '1.0', category: 'metabolic',
    sources: [{ ref: 'EASO/ESPEN Guidelines on Obesity', year: 2022 }],
    conditions: { type: 'FIELD_COMPARE', field: 'bmi', operator: 'GTE', value: 30 },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetKcal', operation: 'ADD', value: -500 },
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'MULTIPLY', value: 1.3 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25, max: 35 },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['fast food', 'słodycze', 'cukierek', 'czekolada', 'chipsy', 'napój gazowany', 'soda', 'cola', 'candy', 'chips', 'chocolate'] },
      { type: 'CLINICAL_NOTE', note: 'Otyłość (BMI ≥30): deficyt 500 kcal/d, białko 1.2-1.5g/kg, błonnik 25-30g/d, preferencja produktów niskoglikemicznych i sycących', category: 'RESTRICTION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000 IU/d', reason: 'Częsty niedobór u osób z otyłością' },
    ],
  },
  // 27.2.2 Zespół metaboliczny
  {
    name: 'Zespół metaboliczny',
    description: 'Kombinacja zaburzeń metabolicznych — dieta śródziemnomorska, ograniczenie cukrów i sodu',
    type: 'POLICY', severity: 'LOW', priority: 79,
    version: '1.0', category: 'metabolic',
    sources: [{ ref: 'IDF Consensus', year: 2006 }, { ref: 'ATP III NCEP' }],
    conditions: { type: 'HAS_CONDITION', terms: ['metabolic_syndrome', 'zespół metaboliczny', 'zespol metaboliczny', 'syndrom metaboliczny'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetKcal', operation: 'ADD', value: -400 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 6 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sodium', scope: 'DAILY_TOTAL', max: 2300 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'saturatedFat', scope: 'DAILY_TOTAL', max: 20 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25 },
      { type: 'MEAL_DISTRIBUTION', nutrient: 'carbs', maxPerMealPct: 30 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'heartFriendly', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cukier', 'dżem', 'syrop', 'słodycze', 'napój gazowany', 'soda', 'sugar', 'candy', 'soda'] },
      { type: 'CLINICAL_NOTE', note: 'Zespół metaboliczny: dieta śródziemnomorska, ograniczenie cukrów prostych i sodu, zwiększony błonnik, redukcja masy ciała', category: 'RESTRICTION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Magnez', dose: '300-400 mg/d', reason: 'Wsparcie insulinowrażliwości i kontroli ciśnienia' },
    ],
  },
  // 27.2.3 Insulinooporność (ULEPSZENIE)
  {
    name: 'Insulinooporność',
    description: 'Pacjent zgłosił insulinooporność — węglowodany 40-45%, niski IG, suplementacja chrom/Mg',
    type: 'POLICY', severity: 'LOW', priority: 80,
    version: '2.0', category: 'metabolic',
    sources: [{ ref: 'PTD (Polskie Towarzystwo Diabetologiczne)', year: 2024 }],
    conditions: { type: 'HAS_CONDITION', terms: ['insulin_resistance', 'insulinooporność', 'insulinoopornosc'] },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetCarbsG', operation: 'MULTIPLY', value: 0.9 },
      { type: 'MEAL_DISTRIBUTION', nutrient: 'carbs', maxPerMealPct: 28 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 6 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'diabeticFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cukier', 'dżem', 'konfitura', 'syrop', 'biały chleb', 'biały ryż', 'sugar', 'jam', 'syrup', 'candy', 'cukierek', 'white bread', 'white rice'] },
      { type: 'CLINICAL_NOTE', note: 'Insulinooporność: węglowodany 40-45% energii, produkty o niskim IG, równomierny rozkład węgli w posiłkach, ograniczenie cukrów prostych', category: 'RESTRICTION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Chrom', dose: '200-400 µg/d', reason: 'Wsparcie wrażliwości na insulinę (PTD 2024)' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Magnez', dose: '300-400 mg/d', reason: 'Poprawa insulinowrażliwości, częsty niedobór' },
    ],
  },
  // 27.2.4 Cukrzyca typu 2 (doprecyzowanie)
  {
    name: 'Cukrzyca typu 2',
    description: 'Pacjent zgłosił cukrzycę typu 2 — węglowodany 45%, niski IG, regularne posiłki',
    type: 'POLICY', severity: 'LOW', priority: 85,
    version: '2.0', category: 'metabolic',
    sources: [{ ref: 'PTD', year: 2024 }, { ref: 'ADA Standards of Care', year: 2024 }],
    conflictsWith: ['Cukrzyca typu 1'],
    conditions: { type: 'HAS_CONDITION', terms: ['diabetes_type2', 'cukrzyca typu 2', 'cukrzyca type 2', 'diabetes type 2', 'diabetes', 'cukrzyca'] },
    effects: [
      { type: 'MEAL_DISTRIBUTION', nutrient: 'carbs', maxPerMealPct: 25 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 5 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25 },
      { type: 'PREFER_PRODUCTS', flagKey: 'diabeticFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cukier', 'dżem', 'syrop', 'słodycze', 'biały chleb', 'biały ryż', 'sugar', 'candy', 'soda', 'cola', 'white bread'] },
      { type: 'CLINICAL_NOTE', note: 'Cukrzyca typu 2: węglowodany 45% energii, niski IG, regularne posiłki (4-5/d), eliminacja cukrów prostych. Źródło: PTD 2024, ADA Standards of Care 2024', category: 'RESTRICTION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Chrom', dose: '200 µg/d', reason: 'Wsparcie kontroli glikemii' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Magnez', dose: '300 mg/d', reason: 'Częsty niedobór u diabetyków' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000 IU/d', reason: 'Wsparcie wrażliwości na insulinę' },
    ],
  },
  // 27.2.5 Cukrzyca typu 1 (NOWA)
  {
    name: 'Cukrzyca typu 1',
    description: 'Pacjent zgłosił cukrzycę typu 1 — wymienniki WW, niski-średni IG',
    type: 'POLICY', severity: 'HIGH', priority: 86,
    version: '1.0', category: 'metabolic',
    sources: [{ ref: 'PTD', year: 2024 }, { ref: 'ISPAD', year: 2022 }],
    conflictsWith: ['Cukrzyca typu 2'],
    conditions: { type: 'HAS_CONDITION', terms: ['diabetes_type1', 'cukrzyca typu 1', 'cukrzyca type 1', 'diabetes type 1'] },
    effects: [
      { type: 'MEAL_DISTRIBUTION', nutrient: 'carbs', maxPerMealPct: 25 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 5 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25 },
      { type: 'PREFER_PRODUCTS', flagKey: 'diabeticFriendly', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cukier', 'dżem', 'syrop', 'słodycze', 'sugar', 'candy', 'soda', 'cola'] },
      { type: 'CLINICAL_NOTE', note: 'Cukrzyca typu 1: wymienniki węglowodanowe (WW), niski-średni IG, regularne posiłki + przekąski, koordynacja z diabetologiem. Źródło: PTD 2024, ISPAD 2022', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'UWAGA: Plan wymaga koordynacji dawek insuliny z diabetologiem. Każdy posiłek powinien mieć podaną liczbę WW.', category: 'WARNING' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Witamina D3', dose: '2000 IU/d', reason: 'Wsparcie autoimmunologiczne i metaboliczne' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Magnez', dose: '300 mg/d', reason: 'Częsty niedobór, wspiera kontrolę glikemii' },
    ],
  },
  // 27.2.6 Stan przedcukrzycowy
  {
    name: 'Stan przedcukrzycowy',
    description: 'Stan przedcukrzycowy — łagodniejsze ograniczenia, redukcja masy 5-7%',
    type: 'POLICY', severity: 'LOW', priority: 77,
    version: '1.0', category: 'metabolic',
    sources: [{ ref: 'PTD', year: 2024 }, { ref: 'ADA Prevention Guidelines' }],
    conditions: { type: 'HAS_CONDITION', terms: ['prediabetes', 'przedcukrzycowy', 'stan przedcukrzycowy', 'nieprawidłowa glikemia'] },
    effects: [
      { type: 'MEAL_DISTRIBUTION', nutrient: 'carbs', maxPerMealPct: 30 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 8 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'fiber', scope: 'DAILY_TOTAL', min: 25 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cukier', 'dżem', 'syrop', 'słodycze', 'napój gazowany', 'sugar', 'candy', 'soda'] },
      { type: 'CLINICAL_NOTE', note: 'Stan przedcukrzycowy: węglowodany 45-50% energii, niski IG, redukcja masy ciała o 5-7% jeśli nadwaga. Źródło: PTD 2024, ADA Prevention Guidelines', category: 'RECOMMENDATION' },
      { type: 'SUGGEST_SUPPLEMENT', name: 'Chrom', dose: '200 µg/d', reason: 'Wsparcie normalizacji glikemii' },
    ],
  },
  // 27.2.7 Hipoglikemia reaktywna
  {
    name: 'Hipoglikemia reaktywna',
    description: 'Hipoglikemia reaktywna — małe częste posiłki, unikanie cukrów prostych',
    type: 'POLICY', severity: 'LOW', priority: 76,
    version: '1.0', category: 'metabolic',
    sources: [{ ref: 'Endocrine Society Guidelines' }],
    conditions: { type: 'HAS_CONDITION', terms: ['reactive_hypoglycemia', 'hipoglikemia reaktywna', 'hipoglikemia', 'reactive hypoglycemia'] },
    effects: [
      { type: 'MEAL_DISTRIBUTION', nutrient: 'carbs', maxPerMealPct: 20 },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 5 },
      { type: 'PREFER_PRODUCTS', flagKey: 'lowSugar', flagValue: true },
      { type: 'PREFER_PRODUCTS', flagKey: 'highFiber', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['cukier', 'dżem', 'syrop', 'miód', 'słodycze', 'sok owocowy', 'napój gazowany', 'sugar', 'candy', 'soda', 'juice', 'honey'] },
      { type: 'CLINICAL_NOTE', note: 'Hipoglikemia reaktywna: małe częste posiłki (5-6/d), białko + tłuszcz przy każdym posiłku, unikanie cukrów prostych, ograniczenie alkoholu. Źródło: Endocrine Society Guidelines', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Zalecane 5-6 posiłków dziennie z równomiernym rozkładem węglowodanów — każdy posiłek musi zawierać białko i tłuszcz dla spowolnienia wchłaniania glukozy', category: 'RECOMMENDATION' },
    ],
  },
  // 27.2.8 Dna moczanowa (ULEPSZENIE)
  {
    name: 'Dna moczanowa',
    description: 'Dna moczanowa — ograniczenie puryn, nawodnienie 2-3L/d, ograniczenie fruktozy',
    type: 'POLICY', severity: 'LOW', priority: 70,
    version: '2.0', category: 'metabolic',
    sources: [{ ref: 'EULAR', year: 2016 }, { ref: 'ACR', year: 2020 }],
    conditions: { type: 'HAS_CONDITION', terms: ['gout', 'dna moczanowa', 'dna'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'goutFriendly', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['podroby', 'wątróbka', 'nerki', 'sardynka', 'szprot', 'anchois', 'piwo', 'alkohol', 'offal', 'liver', 'kidney', 'sardine', 'anchovy', 'sprat', 'beer', 'alcohol'] },
      { type: 'NUTRIENT_LIMIT', nutrient: 'sugar', scope: 'PER_100G', max: 8 },
      { type: 'CLINICAL_NOTE', note: 'Dna moczanowa: ograniczono produkty bogate w puryny (podroby, małe ryby morskie), ograniczenie fruktozy, nawodnienie 2-3L/d, eliminacja alkoholu (zwłaszcza piwa). Źródło: EULAR 2016, ACR 2020', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'W fazie ataku dny: dieta płynna/lekkostrawna, zwiększone nawodnienie, unikanie mięsa i ryb. W remisji: normalna dieta z ograniczeniem puryn.', category: 'INFO' },
    ],
  },
  // 27.2.9 Hiperurykemia
  {
    name: 'Hiperurykemia',
    description: 'Podwyższony kwas moczowy bez objawów dny — łagodne ograniczenie puryn, nawodnienie',
    type: 'POLICY', severity: 'LOW', priority: 65,
    version: '1.0', category: 'metabolic',
    sources: [{ ref: 'ACR', year: 2020 }],
    conditions: { type: 'HAS_CONDITION', terms: ['hyperuricemia', 'hiperurykemia', 'kwas moczowy', 'podwyższony kwas moczowy'] },
    effects: [
      { type: 'PREFER_PRODUCTS', flagKey: 'goutFriendly', flagValue: true },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['podroby', 'wątróbka', 'nerki', 'piwo', 'offal', 'liver', 'kidney', 'beer'] },
      { type: 'CLINICAL_NOTE', note: 'Hiperurykemia: ograniczenie puryn, alkoholu i fruktozy, preferencja nabiału niskotłuszczowego (obniża kwas moczowy), nawodnienie. Źródło: ACR 2020', category: 'RESTRICTION' },
    ],
  },
  // Pregnancy
  {
    name: 'Ciąża',
    description: 'Pacjentka jest w ciąży — zwiększone zapotrzebowanie, wykluczenia bezpieczeństwa',
    type: 'POLICY', severity: 'LOW', priority: 95,
    conditions: { type: 'FIELD_EQUALS', field: 'pregnancyStatus', value: 'pregnant' },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetKcal', operation: 'ADD', value: 300 },
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'ADD', value: 25 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['sushi', 'surowe mięso', 'tatar', 'surowe ryby', 'raw fish', 'raw meat', 'steak tartare'] },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'wino', 'piwo', 'alcohol', 'wine', 'beer'] },
      { type: 'CLINICAL_NOTE', note: 'Ciąża: +300 kcal/dzień, +25g białka, wykluczono surowe mięso/ryby i alkohol', category: 'RESTRICTION' },
      { type: 'CLINICAL_NOTE', note: 'Ciąża: zalecana suplementacja kwasu foliowego, żelaza i DHA — skonsultuj z lekarzem', category: 'RECOMMENDATION' },
    ],
  },
  {
    name: 'Karmienie piersią',
    description: 'Pacjentka karmi piersią — zwiększone zapotrzebowanie kaloryczne',
    type: 'POLICY', severity: 'LOW', priority: 90,
    conditions: { type: 'FIELD_EQUALS', field: 'pregnancyStatus', value: 'breastfeeding' },
    effects: [
      { type: 'MODIFY_TARGETS', field: 'targetKcal', operation: 'ADD', value: 500 },
      { type: 'MODIFY_TARGETS', field: 'targetProteinG', operation: 'ADD', value: 20 },
      { type: 'EXCLUDE_KEYWORDS', keywords: ['alkohol', 'alcohol', 'wino', 'wine', 'piwo', 'beer'] },
      { type: 'CLINICAL_NOTE', note: 'Karmienie piersią: +500 kcal/dzień, +20g białka, wykluczono alkohol', category: 'RESTRICTION' },
    ],
  },
];
